[profile.ci.fuzz]
runs = 10_000

[rpc_endpoints]
base_goerli = "${RPC_BASE}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
base_goerli = { key = "${ETHERSCAN_API_KEY}", chain = 84531, url = "https://goerli.basescan.org" }
